#!/usr/bin/env python3
"""
generate_env_sh.py

Read a YAML config file and emit a shell script with safe export statements.
Designed to be run during provisioning to create /etc/profile.d/fusioncloudx.sh
or to emit to stdout for atomic installation by a wrapper script.

Usage:
  python3 modules/generate_env_sh.py config/bootstrap.yaml > /tmp/fusioncloudx.sh

The script will uppercase and sanitize variable names (A-Z0-9 and underscores).
It converts booleans to 'true'/'false' and escapes single quotes in values.
"""

import sys
import yaml
import re
from pathlib import Path


def sanitize_name(name: str) -> str:
    name = name.upper()
    # replace any non-alphanumeric with underscore
    name = re.sub(r'[^A-Z0-9]', '_', name)
    # collapse multiple underscores
    name = re.sub(r'_+', '_', name)
    return name


def quote_value(val) -> str:
    # Convert Python types to shell-safe single-quoted strings
    if isinstance(val, bool):
        sval = 'true' if val else 'false'
    else:
        sval = str(val)
    # Escape single quotes for single-quoted shell string: ' -> '\''
    sval_escaped = sval.replace("'", "'\"'\"'")
    return f"'{sval_escaped}'"


def generate_lines(data: dict):
    lines = ["# Generated by FusionCloudX - do not edit manually", "# Source: config/bootstrap.yaml", ""]
    if not isinstance(data, dict):
        return lines
    for cat, val in data.items():
        if isinstance(val, dict):
            for k, v in val.items():
                name = sanitize_name(f"{cat}_{k}")
                lines.append(f"export {name}={quote_value(v)}")
        else:
            name = sanitize_name(str(cat))
            lines.append(f"export {name}={quote_value(val)}")
    lines.append("")
    return lines


def main():
    if len(sys.argv) < 2:
        print("Usage: generate_env_sh.py <path/to/bootstrap.yaml>", file=sys.stderr)
        sys.exit(2)
    yaml_path = Path(sys.argv[1])
    if not yaml_path.exists():
        print(f"YAML config not found: {yaml_path}", file=sys.stderr)
        sys.exit(3)
    try:
        data = yaml.safe_load(yaml_path.read_text())
    except Exception as e:
        print(f"Failed to parse YAML: {e}", file=sys.stderr)
        sys.exit(4)
    lines = generate_lines(data or {})
    sys.stdout.write("\n".join(lines))


if __name__ == '__main__':
    main()
